version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: tegrkiq
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - tegrkiq-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - tegrkiq-redis:/var/lib/redis/data
  tegrkiq:
    image: $DOCKER_USERNAME/dockerizing-tegrkiq:latest
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
  sidekiq:
    image: $DOCKER_USERNAME/tegr-front:latest
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env
  nginx:
    image: $DOCKER_USERNAME/tegr-front:latest
    links:
      - tegrkiq
    ports:
      - '8020:8020'
volumes:
  tegrkiq-postgres:
  tegrkiq-redis: